//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiwiprod_iteration1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class searchDBEntities : DbContext
    {
        public searchDBEntities()
            : base("name=searchDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeSet> AgeSet { get; set; }
        public virtual DbSet<EducationLevelSet> EducationLevelSet { get; set; }
        public virtual DbSet<LocationSet> LocationSet { get; set; }
        public virtual DbSet<SkillsSet> SkillsSet { get; set; }
        public virtual DbSet<degreeEmployment> degreeEmployment { get; set; }
    }
}
